/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall cpuinfo_init(__int64 a1, __int64 a2);
__int64 cpuinfo_exit();
__int64 __fastcall cpuinfo_ctl0(__int64 a1, __int64 a2, __int64 n8);
unsigned __int64 __fastcall after_openat(unsigned __int64 n64, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8, __int64 a9);
__int64 __fastcall before_openat(__int64 a1);
char *__fastcall before_close(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8, __int64 a9);
__int64 *__fastcall before_read(__int64 a1);
// __int64 __fastcall compat_copy_to_user(_QWORD, _QWORD p_enabled, _QWORD n8); idb

//-------------------------------------------------------------------------
// Data declarations

char fake_cpuinfo[1516] = "Processor       : AArch64 Processor rev 0 (aarch64)\nFeatures        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp\nCPU implementer : 0x48\nCPU architecture: 8\nCPU variant     : 0x1\nCPU part        : 0xd0c\nCPU revision    : 0\n\nprocessor       : 0\nBogoMIPS        : 26.00\nCPU implementer : 0x48\nCPU architecture: 8\nCPU variant     : 0x1\nCPU part        : 0xd0c\nCPU revision    : 0\n\nprocessor       : 1\nBogoMIPS        : 26.00\nCPU implementer : 0x48\nCPU architecture: 8\nCPU variant     : 0x2\nCPU part        : 0xd0a\nCPU revision    : 0\n\nprocessor       : 2\nBogoMIPS        : 26.00\nCPU implementer : 0x48\nCPU architecture: 8\nCPU variant     : 0x2\nCPU part        : 0xd0a\nCPU revision    : 0\n\nprocessor       : 3\nBogoMIPS        : 26.00\nCPU implementer : 0x48\nCPU architecture: 8\nCPU variant     : 0x2\nCPU part        : 0xd0a\nCPU revision    : 0\n\nprocessor       : 4\nBogoMIPS        : 26.00\nCPU implementer : 0x48\nCPU architecture: 8\nCPU variant     : 0x3\nCPU part        : 0xd0b\nCPU revision    : 0\n\nprocessor       : 5\nBogoMIPS        : 26.00\nCPU implementer : 0x48\nCPU architecture: 8\nCPU variant     : 0x3\nCPU part        : 0xd0b\nCPU revision    : 0\n\nprocessor       : 6\nBogoMIPS        : 26.00\nCPU implementer : 0x48\nCPU architecture: 8\nCPU variant     : 0x3\nCPU part        : 0xd0b\nCPU revision    : 0\n\nprocessor       : 7\nBogoMIPS        : 26.00\nCPU implementer : 0x48\nCPU architecture: 8\nCPU variant     : 0x3\nCPU part        : 0xd0b\nCPU revision    : 0\n\nHardware        : HiSilicon Kirin 9020\n"; // weak
_UNKNOWN unk_BD0; // weak
_UNKNOWN unk_C00; // weak
_UNKNOWN unk_C28; // weak
_UNKNOWN unk_C48; // weak
_UNKNOWN unk_C68; // weak
char aProcCpuinfo[14] = "/proc/cpuinfo"; // weak
char aCpuinfo[8] = "cpuinfo"; // weak
int module_enabled[]; // weak
_QWORD tracked_fds[192]; // weak
// extern _UNKNOWN thread_size; weak
// extern _UNKNOWN sp_el0_is_thread_info; weak
// extern _UNKNOWN hook_syscalln; weak
// extern _UNKNOWN sp_el0_is_current; weak
// extern _UNKNOWN task_in_thread_info_offset; weak
// extern __int64 (__fastcall *printk)(_QWORD, _QWORD, _QWORD); weak
// extern _UNKNOWN thread_info_in_task; weak
// extern _UNKNOWN has_syscall_wrapper; weak
// extern _UNKNOWN compat_strncpy_from_user; weak
// extern _UNKNOWN unhook_syscalln; weak


//----- (0000000000000000) ----------------------------------------------------
__int64 __fastcall cpuinfo_init(__int64 a1, __int64 a2)
{
  unsigned int v2; // w0
  unsigned int v3; // w0
  unsigned int v4; // w0

  printk(&unk_BD0, a2, a1);
  module_enabled[0] = 1;
  v2 = hook_syscalln(56, 4, before_openat, after_openat, 0);
  if ( v2 )
    printk(&unk_C00, v2, printk);
  v3 = hook_syscalln(63, 3, before_read, 0, 0);
  if ( v3 )
    printk(&unk_C28, v3, printk);
  v4 = hook_syscalln(57, 1, before_close, 0, 0);
  if ( v4 )
    printk(&unk_C48, v4, printk);
  return 0;
}
// D40: using guessed type int module_enabled[];
// D48: using guessed type _QWORD tracked_fds[192];
// 1378: using guessed type __int64 (__fastcall *printk)(_QWORD, _QWORD, _QWORD);

//----- (00000000000000E0) ----------------------------------------------------
__int64 cpuinfo_exit()
{
  __int64 v0; // x2

  unhook_syscalln(56, before_openat, after_openat);
  unhook_syscalln(63, before_read, 0);
  unhook_syscalln(57, before_close, 0);
  printk(&unk_C68, printk, v0);
  return 0;
}
// 138: variable 'v0' is possibly undefined
// 1378: using guessed type __int64 (__fastcall *printk)(_QWORD, _QWORD, _QWORD);

//----- (0000000000000148) ----------------------------------------------------
__int64 __fastcall cpuinfo_ctl0(__int64 a1, __int64 a2, __int64 n8)
{
  bool v3; // cc

  if ( a2 )
    v3 = (int)n8 <= 0;
  else
    v3 = 1;
  if ( v3 )
    return 0;
  if ( (int)n8 > 8 )
    n8 = 8;
  else
    n8 = (unsigned int)n8;
  compat_copy_to_user(a2, "enabled", n8);
  return 0;
}

//----- (000000000000018C) ----------------------------------------------------
unsigned __int64 __fastcall after_openat(
        unsigned __int64 n64,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8,
        __int64 a9)
{
  __int64 v9; // x4
  unsigned __int64 StatusReg; // x3
  _QWORD *p_tracked_fds; // x5
  _DWORD *p_tracked_fds_1; // x1
  unsigned __int64 v13; // x0

  if ( *(_QWORD *)(n64 + 16) )
  {
    v9 = *(_QWORD *)(n64 + 80);
    if ( (v9 & 0x8000000000000000LL) == 0 )
    {
      if ( sp_el0_is_current )
      {
        StatusReg = _ReadStatusReg(SP_EL0);
      }
      else
      {
        if ( thread_info_in_task | sp_el0_is_thread_info )
          v13 = _ReadStatusReg(SP_EL0);
        else
          v13 = -thread_size & (unsigned __int64)&a9;
        StatusReg = *(_QWORD *)(task_in_thread_info_offset + v13);
      }
      p_tracked_fds = &tracked_fds;
      LODWORD(n64) = 0;
      p_tracked_fds_1 = &tracked_fds;
      while ( *(_QWORD *)p_tracked_fds_1 != StatusReg || (_DWORD)v9 != p_tracked_fds_1[2] )
      {
        LODWORD(n64) = n64 + 1;
        p_tracked_fds_1 += 6;
        if ( (_DWORD)n64 == 64 )
        {
          LODWORD(n64) = 0;
          while ( *p_tracked_fds )
          {
            n64 = (unsigned int)(n64 + 1);
            p_tracked_fds += 3;
            if ( (_DWORD)n64 == 64 )
              return n64;
          }
          break;
        }
      }
      n64 = (unsigned __int64)&tracked_fds + 24 * (unsigned int)n64;
      *(_QWORD *)n64 = StatusReg;
      *(_DWORD *)(n64 + 8) = v9;
      *(_QWORD *)(n64 + 16) = 0;
    }
  }
  return n64;
}

//----- (0000000000000280) ----------------------------------------------------
__int64 __fastcall before_openat(__int64 a1)
{
  __int64 v2; // x0
  __int64 v3; // x1
  __int64 module_enabled; // x0
  int n99_1; // w4
  int n47_1; // w2
  int n47; // w3
  __int64 n13; // x1
  _BYTE *v9; // x2
  __int64 n7; // x1
  int n99; // w2
  _BYTE *v12; // x2
  _BYTE v13[128]; // [xsp+20h] [xbp+20h] BYREF

  v2 = a1 + 88;
  if ( has_syscall_wrapper )
    v2 = *(_QWORD *)(a1 + 88);
  v3 = *(_QWORD *)(v2 + 8);
  *(_QWORD *)(a1 + 16) = 0;
  v13[0] = 0;
  module_enabled = compat_strncpy_from_user(v13, v3, 128);
  if ( module_enabled > 0 )
  {
    n99_1 = v13[0];
    v13[127] = 0;
    if ( v13[0] )
    {
      n47_1 = v13[0];
      n47 = 47;
      n13 = 0;
      do
      {
        if ( n47_1 != n47 )
          goto LABEL_12;
        v9 = &v13[n13++];
        n47_1 = (unsigned __int8)v9[1];
        n47 = (unsigned __int8)aProcCpuinfo[n13];
      }
      while ( n47_1 && n13 != 13 );
      if ( n47_1 == n47 )
      {
LABEL_10:
        module_enabled = (unsigned int)::module_enabled;
        if ( ::module_enabled )
        {
          module_enabled = 1;
          *(_QWORD *)(a1 + 16) = 1;
        }
        return module_enabled;
      }
LABEL_12:
      n7 = 0;
      module_enabled = (__int64)"cpuinfo";
      n99 = 99;
      do
      {
        if ( n7 == 7 )
          break;
        if ( n99_1 != n99 )
          return module_enabled;
        v12 = &v13[n7++];
        n99_1 = (unsigned __int8)v12[1];
        n99 = (unsigned __int8)aCpuinfo[n7];
      }
      while ( n99_1 );
      if ( n99 == n99_1 )
        goto LABEL_10;
    }
  }
  return module_enabled;
}
// D40: using guessed type int module_enabled;

//----- (0000000000000380) ----------------------------------------------------
char *__fastcall before_close(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8,
        __int64 a9)
{
  __int64 v9; // x4
  unsigned __int64 v10; // x3
  char *p_tracked_fds; // x0
  int n64; // w1
  __int64 v13; // x0
  unsigned __int64 StatusReg; // x0

  if ( !has_syscall_wrapper )
  {
    v9 = *(_QWORD *)(a1 + 88);
    if ( sp_el0_is_current )
      goto LABEL_3;
LABEL_10:
    if ( thread_info_in_task | sp_el0_is_thread_info )
      StatusReg = _ReadStatusReg(SP_EL0);
    else
      StatusReg = -thread_size & (unsigned __int64)&a9;
    v10 = *(_QWORD *)(task_in_thread_info_offset + StatusReg);
    goto LABEL_4;
  }
  v9 = **(_QWORD **)(a1 + 88);
  if ( !sp_el0_is_current )
    goto LABEL_10;
LABEL_3:
  v10 = _ReadStatusReg(SP_EL0);
LABEL_4:
  p_tracked_fds = (char *)&tracked_fds;
  n64 = 0;
  while ( *(_QWORD *)p_tracked_fds != v10 || (_DWORD)v9 != *((_DWORD *)p_tracked_fds + 2) )
  {
    ++n64;
    p_tracked_fds += 24;
    if ( n64 == 64 )
      return p_tracked_fds;
  }
  v13 = 24LL * n64;
  *(_QWORD *)((char *)&tracked_fds + v13) = 0;
  p_tracked_fds = (char *)&tracked_fds + v13;
  *((_DWORD *)p_tracked_fds + 2) = 0;
  *((_QWORD *)p_tracked_fds + 2) = 0;
  return p_tracked_fds;
}

//----- (0000000000000460) ----------------------------------------------------
__int64 *__fastcall before_read(__int64 a1)
{
  __int64 v1; // x6
  __int64 *result; // x0
  __int64 v3; // x5
  unsigned __int64 v4; // x4
  _DWORD *p_tracked_fds; // x1
  int n64; // w2
  __int64 n64_1; // x5
  unsigned __int64 n0x5EA; // x1
  unsigned __int64 n8; // x4
  unsigned __int64 StatusReg; // x1
  __int64 v11; // x0
  __int64 v12; // [xsp+0h] [xbp+0h] BYREF
  unsigned __int64 n8_1; // [xsp+10h] [xbp+10h]
  __int64 v14; // [xsp+18h] [xbp+18h]
  char *v15; // [xsp+20h] [xbp+20h]
  __int64 n64_2; // [xsp+28h] [xbp+28h]

  v1 = a1;
  if ( !has_syscall_wrapper )
  {
    result = (__int64 *)(a1 + 88);
    v3 = *(_QWORD *)(v1 + 88);
    if ( sp_el0_is_current )
      goto LABEL_3;
LABEL_15:
    if ( thread_info_in_task | sp_el0_is_thread_info )
      StatusReg = _ReadStatusReg(SP_EL0);
    else
      StatusReg = -thread_size & (unsigned __int64)&v12;
    v4 = *(_QWORD *)(task_in_thread_info_offset + StatusReg);
    goto LABEL_4;
  }
  result = *(__int64 **)(a1 + 88);
  v3 = *result;
  if ( !sp_el0_is_current )
    goto LABEL_15;
LABEL_3:
  v4 = _ReadStatusReg(SP_EL0);
LABEL_4:
  p_tracked_fds = tracked_fds;
  n64 = 0;
  while ( v4 != *(_QWORD *)p_tracked_fds || (_DWORD)v3 != p_tracked_fds[2] )
  {
    ++n64;
    p_tracked_fds += 6;
    if ( n64 == 64 )
      return result;
  }
  if ( module_enabled[0] )
  {
    n64_1 = n64;
    n0x5EA = tracked_fds[3 * n64 + 2];
    if ( n0x5EA > 0x5EA )
    {
      result = (_QWORD *)(cpuinfo_init + 1);
      *(_DWORD *)(v1 + 8) = 1;
      *(_QWORD *)(v1 + 80) = 0;
    }
    else
    {
      n8 = 1515 - n0x5EA;
      if ( 1515 - n0x5EA > result[2] )
        n8 = result[2];
      if ( !n8 )
        goto LABEL_13;
      v11 = result[1];
      n8_1 = n8;
      v14 = v1;
      v15 = (char *)&tracked_fds[3 * n64];
      n64_2 = n64;
      result = (__int64 *)compat_copy_to_user(v11, &fake_cpuinfo[n0x5EA], (unsigned int)n8);
      if ( (int)result > 0 )
      {
        n64_1 = n64_2;
        n8 = n8_1;
        v1 = v14;
        n0x5EA = *((_QWORD *)v15 + 2);
LABEL_13:
        *(_QWORD *)&module_enabled[6 * n64_1 + 6] = n8 + n0x5EA;
        result = (_QWORD *)(cpuinfo_init + 1);
        *(_DWORD *)(v1 + 8) = 1;
        *(_QWORD *)(v1 + 80) = n8;
      }
    }
  }
  return result;
}
// 0: using guessed type __int64 __fastcall cpuinfo_init();
// D40: using guessed type int module_enabled[];
// D48: using guessed type _QWORD tracked_fds[192];

// nfuncs=11 queued=7 decompiled=7 lumina nreq=0 worse=0 better=0
// ALL OK, 7 function(s) have been successfully decompiled
